"""
Friday LQE HTML Report Generator

Generates professional HTML reports for Friday night low quality escalation analysis
matching the risk report template style.

Author: Carter Ryan
Created: February 5, 2026
"""

import json
import os
from datetime import datetime
from typing import Dict, List, Any


class FridayLQEHTMLGenerator:
    """Generator for HTML reports matching the risk report template style."""
    
    def __init__(self):
        """Initialize the HTML generator."""
        self.template_header = self._get_template_header()
        self.template_footer = self._get_template_footer()
    
    def _get_template_header(self) -> str:
        """Get HTML header with Office compatibility and styles."""
        return """<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=unicode">
<meta name=ProgId content=Word.Document>
<meta name=Generator content="PHEPy Friday LQE Reporter">
<title>Weekly Low Quality Escalations for Review</title>
<style>
<!--
body {
    font-family: Calibri, sans-serif;
    font-size: 11pt;
    line-height: 1.5;
}
h1 {
    font-size: 16pt;
    font-weight: bold;
    color: #1F497D;
    margin-bottom: 10pt;
}
h2 {
    font-size: 14pt;
    font-weight: bold;
    color: #1F497D;
    margin-top: 15pt;
    margin-bottom: 10pt;
}
h3 {
    font-size: 12pt;
    font-weight: bold;
    color: #1F497D;
    margin-top: 12pt;
    margin-bottom: 8pt;
}
table {
    border-collapse: collapse;
    width: 100%;
    margin: 10pt 0;
}
th {
    background-color: #B7D9F7;
    border: 1pt solid #7EA8F8;
    padding: 4.5pt;
    font-weight: bold;
    text-align: left;
    font-size: 9pt;
}
td {
    border: 1pt solid #7EA8F8;
    padding: 4.5pt;
    font-size: 9pt;
    vertical-align: top;
}
.summary-table {
    width: 60%;
    margin: 15pt 0;
}
.summary-table th:nth-child(1) { width: 25%; }  /* Region */
.summary-table th:nth-child(2) { width: 15%; }  /* Total */
.summary-table th:nth-child(3) { width: 60%; }  /* Breakdown */
.escalation-table {
    width: 100%;
    font-size: 9pt;
}
.escalation-table th:nth-child(1) { width: 10%; }  /* Incident ID */
.escalation-table th:nth-child(2) { width: 45%; }  /* Title */
.escalation-table th:nth-child(3) { width: 20%; }  /* Created By */
.escalation-table th:nth-child(4) { width: 12%; }  /* Resolved */
.escalation-table th:nth-child(5) { width: 13%; }  /* Quality Issue */
.escalation-table td {
    word-wrap: break-word;
    overflow-wrap: break-word;
}
.header-info {
    margin: 10pt 0;
    border-bottom: 1pt solid #D9D9D9;
    padding-bottom: 10pt;
}
.severity-critical {
    background-color: #FFC7CE;
    font-weight: bold;
}
.severity-high {
    background-color: #FFE699;
}
.severity-medium {
    background-color: #C6EFCE;
}
.severity-low {
    background-color: #E7E6E6;
}
.region-section {
    margin-top: 20pt;
    page-break-inside: avoid;
}
.feature-section {
    margin-top: 15pt;
    margin-left: 15pt;
}
.emoji {
    font-family: "Segoe UI Emoji", sans-serif;
}
.icm-link {
    color: #0563C1;
    text-decoration: underline;
}
.quality-badge {
    padding: 2pt 6pt;
    border-radius: 3pt;
    font-size: 8pt;
    font-weight: bold;
    color: white;
}
.quality-missing-diag {
    background-color: #E74C3C;
}
.quality-insufficient {
    background-color: #F39C12;
}
.quality-missing-context {
    background-color: #3498DB;
}
-->
</style>
</head>
<body>
"""
    
    def _get_template_footer(self) -> str:
        """Get HTML footer."""
        return """
<p style="margin-top: 30pt; padding-top: 15pt; border-top: 1pt solid #D9D9D9; font-size: 9pt; color: #808080;">
    <i>This report was automatically generated by the PHEPy Friday LQE Analysis System.</i><br>
    For questions or issues, contact the Purview Support Leadership team.
</p>
</body>
</html>
"""
    
    def _get_severity_class(self, severity: int) -> str:
        """Get CSS class for severity coloring."""
        if severity <= 2:
            return "severity-critical"
        elif severity == 3:
            return "severity-high"
        elif severity == 4:
            return "severity-medium"
        else:
            return "severity-low"
    
    def _get_quality_icon(self, quality_reason: str) -> str:
        """Get emoji icon for quality reason."""
        reason_lower = quality_reason.lower() if quality_reason else ""
        
        if "diagnostic" in reason_lower or "logs" in reason_lower:
            return '<span class="emoji">🔍</span>'
        elif "investigation" in reason_lower or "tsg" in reason_lower:
            return '<span class="emoji">🔬</span>'
        elif "context" in reason_lower or "business impact" in reason_lower:
            return '<span class="emoji">📋</span>'
        elif "customer" in reason_lower:
            return '<span class="emoji">👤</span>'
        else:
            return '<span class="emoji">⚠️</span>'
    
    def _get_region_icon(self, region: str) -> str:
        """Get emoji icon for region."""
        region_icons = {
            "Americas": '<span class="emoji">🌎</span>',
            "EMEA": '<span class="emoji">🌍</span>',
            "APAC": '<span class="emoji">🌏</span>',
            "LATAM": '<span class="emoji">🌎</span>',
            "Unknown": '<span class="emoji">🌐</span>'
        }
        return region_icons.get(region, '<span class="emoji">🌐</span>')
    
    def _get_feature_icon(self, feature: str) -> str:
        """Get emoji icon for feature area."""
        feature_icons = {
            "MIP/DLP": '<span class="emoji">🔒</span>',
            "DLM": '<span class="emoji">📦</span>',
            "eDiscovery": '<span class="emoji">🔎</span>',
            "Compliance": '<span class="emoji">✅</span>',
            "Other": '<span class="emoji">📁</span>',
            "Unknown": '<span class="emoji">❓</span>'
        }
        return feature_icons.get(feature, '<span class="emoji">📁</span>')
    
    def generate_report(self, data: Dict[str, Any], output_path: str = None) -> str:
        """
        Generate HTML report from Friday LQE data.
        
        Args:
            data: Dictionary containing report data (from JSON file or agent)
            output_path: Path for output HTML file
            
        Returns:
            Path to generated HTML file
        """
        if output_path is None:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            output_path = f'friday_lq_report_{timestamp}.htm'
        
        # Build HTML content
        html = self.template_header
        
        # Add header section
        html += self._generate_header_section(data)
        
        # Add executive summary
        html += self._generate_executive_summary(data)
        
        # Add escalations by region
        html += self._generate_escalations_by_region(data)
        
        # Add footer
        html += self.template_footer
        
        # Write to file
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html)
        
        print(f"HTML report generated: {output_path}")
        return output_path
    
    def _generate_header_section(self, data: Dict[str, Any]) -> str:
        """Generate report header with metadata."""
        metadata = data.get('report_metadata', {})
        
        html = '<div class="header-info">\n'
        html += f'<h1>Weekly Low Quality Escalations for Review</h1>\n'
        html += f'<p><b>Report Date:</b> {datetime.now().strftime("%A, %B %d, %Y")}</p>\n'
        html += f'<p><b>Report Period:</b> {metadata.get("period_start", "N/A")} to {metadata.get("period_end", "N/A")} ({metadata.get("period_days", 7)} days)</p>\n'
        html += f'<p><b>Generated:</b> {metadata.get("generated_date", datetime.now().isoformat())}</p>\n'
        html += '</div>\n'
        
        return html
    
    def _generate_executive_summary(self, data: Dict[str, Any]) -> str:
        """Generate executive summary with counts and breakdown."""
        summary = data.get('executive_summary', {})
        total = summary.get('total_escalations', 0)
        regions_count = summary.get('regions_affected', 0)
        by_region = summary.get('by_region', {})
        
        html = '<h2>Executive Summary</h2>\n'
        html += f'<p>We identified <b>{total} unassigned low quality escalations</b> that require reviewer assignment.</p>\n'
        html += f'<p><b>Regions Affected:</b> {regions_count}</p>\n'
        
        # Summary table
        html += '<table class="summary-table">\n'
        html += '<tr><th>Region</th><th>Total</th><th>Feature Breakdown</th></tr>\n'
        
        for region in sorted(by_region.keys()):
            region_data = by_region[region]
            region_total = region_data.get('total', 0)
            by_feature = region_data.get('by_feature', {})
            
            feature_text = ', '.join([f'{feat}: {count}' for feat, count in sorted(by_feature.items())])
            
            html += f'<tr>\n'
            html += f'  <td><b>{region}</b></td>\n'
            html += f'  <td><b>{region_total}</b></td>\n'
            html += f'  <td>{feature_text}</td>\n'
            html += f'</tr>\n'
        
        html += '</table>\n'
        
        return html
    
    def _generate_escalations_by_region(self, data: Dict[str, Any]) -> str:
        """Generate detailed escalation tables organized by region and feature."""
        escalations = data.get('escalations_by_region', {})
        
        html = '<h2>Escalations by Region & Feature Area</h2>\n'
        
        for region in sorted(escalations.keys()):
            features = escalations[region]
            region_total = sum(len(escs) for escs in features.values())
            
            html += f'<div class="region-section">\n'
            html += f'<h2>{region} ({region_total} Escalations)</h2>\n'
            
            for feature in sorted(features.keys()):
                escalation_list = features[feature]
                
                html += f'<div class="feature-section">\n'
                html += f'<h3>{feature} ({len(escalation_list)} cases)</h3>\n'
                
                # Create table for this feature area
                html += '<table class="escalation-table">\n'
                html += '<tr>\n'
                html += '  <th>Incident ID</th>\n'
                html += '  <th>Title</th>\n'
                html += '  <th>Created By</th>\n'
                html += '  <th>Resolved</th>\n'
                html += '  <th>Quality Issue</th>\n'
                html += '</tr>\n'
                
                for esc in escalation_list:
                    icm_id = esc.get('IcMId', 'N/A')
                    icm_link = f'<a href="https://portal.microsofticm.com/imp/v3/incidents/details/{icm_id}" class="icm-link" target="_blank">{icm_id}</a>' if icm_id != 'N/A' else 'N/A'
                    
                    resolved_date = esc.get('ResolveDate', '')
                    if resolved_date:
                        try:
                            resolved_date = datetime.fromisoformat(resolved_date).strftime('%m/%d/%Y')
                        except:
                            pass
                    
                    html += f'<tr>\n'
                    html += f'  <td>{icm_link}</td>\n'
                    html += f'  <td>{esc.get("Title", "No title")}</td>\n'
                    html += f'  <td>{esc.get("CreatedBy", "Unknown")}</td>\n'
                    html += f'  <td>{resolved_date}</td>\n'
                    html += f'  <td>{esc.get("EscalationQuality", "Unknown")}</td>\n'
                    html += f'</tr>\n'
                
                html += '</table>\n'
                html += '</div>\n'  # End feature-section
            
            html += '</div>\n'  # End region-section
        
        return html


def generate_friday_html_report(json_file: str, output_file: str = None) -> str:
    """
    Convenience function to generate HTML report from JSON file.
    
    Args:
        json_file: Path to JSON report file from Friday analysis
        output_file: Optional output path for HTML file
        
    Returns:
        Path to generated HTML file
    """
    # Load JSON data
    with open(json_file, 'r') as f:
        data = json.load(f)
    
    # Generate HTML
    generator = FridayLQEHTMLGenerator()
    
    # Default output path based on JSON filename
    if output_file is None:
        base_name = os.path.splitext(json_file)[0]
        output_file = f'{base_name}.htm'
    
    return generator.generate_report(data, output_file)


if __name__ == "__main__":
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python friday_lq_html_generator.py <json_file> [output_file]")
        print("\nExample:")
        print("  python friday_lq_html_generator.py friday_reports/friday_lq_report_20260205.json")
        sys.exit(1)
    
    json_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else None
    
    try:
        result = generate_friday_html_report(json_file, output_file)
        print(f"\n✅ HTML report generated successfully!")
        print(f"   Output: {result}")
    except Exception as e:
        print(f"\n❌ Error generating HTML report: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
